# Generated by Django 5.0.3 on 2024-07-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
